AWS_UPLOAD_BUCKET = "s3-fundoo-bucket"

AWS_UPLOAD_USERNAME = "s3-fundoo-user"

AWS_UPLOAD_GROUP = "s3-fundoo-group"

AWS_UPLOAD_REGION = "US-East"

AWS_UPLOAD_ACCESS_KEY_ID = "AKIAQHBF74ELFD5T5EJC"

AWS_UPLOAD_SECRET_KEY = "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"

