# Generated by Django 2.2.5 on 2019-10-01 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForgetPassword',
            new_name='ForgotPassword',
        ),
        migrations.RenameModel(
            old_name='User_Login',
            new_name='UserLogin',
        ),
    ]
