# Generated by Django 2.2.7 on 2019-12-01 06:56

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundoonote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundoonote',
            name='change_color',
            field=colorful.fields.RGBColorField(blank=True, colors=['#FFFFFF'], null=True),
        ),
    ]
