# Generated by Django 2.2.6 on 2019-10-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0004_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_body', models.CharField(max_length=100)),
                ('note_file', models.FileField(upload_to='')),
                ('note_title', models.CharField(max_length=100)),
            ],
        ),
    ]
