# Generated by Django 2.2.6 on 2019-10-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooNote', '0003_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_body',
            field=models.TextField(max_length=100),
        ),
    ]
