# Generated by Django 2.2.6 on 2019-11-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_delete_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgotPassword',
        ),
    ]
