# Generated by Django 2.2.6 on 2019-11-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_delete_forgotpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
